### ISSUE TITLE
Full payload available from Jenkins pipeline?

### ISSUE THREAD

**Issue by DeWaRs1206** [utec/easy-webhook-plugin#1]
Hello,

Is it possible to access the full payload from the Jenkins pipeline? I see in the doc only 

- repositoryName
- branchName
- changeNotes
- actorName
- gitCloneUrlHttpsPrefix
- gitCloneUrlSshPrefix

Thanks for your answer and you work, this looks very promising !

Regards 

DeWaRs

**Comment by jrichardsz** [comment]
Thanks for review this plugin.

Do you mean to get all the json payload as a variable? 
Or do you need to extract another values from json payload?

Regards

**Comment by DeWaRs1206** [comment]
I guess having all the json payload accessible will give more flexibility. I will probably need additionnal values in the near futur and I guess this is the easiest way to proceed, ie parse the payload in the Jenkins job directly. 

Regards

**Comment by jrichardsz** [comment]
You are right. I will add this new variable. Thanks!!

If you wish, could fork the project, add this improve and perform a pull request.

I would be happy to help you in the required workspace configurations.

Regards

**Comment by DeWaRs1206** [comment]
I would love to contribute in such project but unfortunately I'm not a Java developer. I had a look before I raised this question to see if I could fix this myself, but unfortunately I couldn't.

**Comment by jrichardsz** [comment]
I made several changes.
Please could you update your PR?
- Revert all your chages
- Update from master
- Add this code just before line 90 ( ParametersAction parametersAction = JenkinsUtil.simpleMapToParametersAction ) in .../src/main/java/org/jrichardsz/jenkins/plugins/easywebhook/WebhookExecutor.java

```
if(SystemPluginConfiguration.getCurrentProperties().isInjectAllWebhookPayload()) {
  parametersToSendItToJob.put("webhookPayload", webhookPayload);  
}
```

As you can see, I added a new configuration called : **Inject all the webhook payload?** which allows the user to choose if he wants this variable.

Thanks

**Comment by jrichardsz** [comment]
Added in v1.0.0.RELEASE
